### ISSUE TITLE
Its up to Date ???

### ISSUE THREAD

**Issue by cronex2011** [SnaBe/steam-bot-constructor#1]
Hey men, i testet your contruct but its not up to date i think.
bc it comes many errors:

/Steambooster/steam-bot-constructor# node app.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'steam-totp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/Steambooster/steam-bot-constructor/app.js:1:81)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

can you help me ?

**Comment by SnaBe** [comment]
None of my projects come packed with the needed modules since they are quite large files. Error: Cannot find module 'steam-totp' is because you've not installed the needed module steam-totp.  Please install steam-totp using npm and return if you any other errors.

**Comment by cronex2011** [comment]
okay okay i fixed it, but new problems:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: InvalidPassword
    at SteamUser._handlers.(anonymous function) (/root/Steambooster/steam-bot-constructor/node_modules/steam-user/components/logon.js:363:16)
    at SteamUser._handleMessage (/root/Steambooster/steam-bot-constructor/node_modules/steam-user/components/messages.js:249:30)
    at CMClient.emit (events.js:189:13)
    at CMClient._netMsgReceived (/root/Steambooster/steam-bot-constructor/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (/root/Steambooster/steam-bot-constructor/node_modules/steam-client/lib/cm_client.js:609:8)
    at CMClient._netMsgReceived (/root/Steambooster/steam-bot-constructor/node_modules/steam-client/lib/cm_client.js:305:24)
    at TCPConnection.emit (events.js:189:13)
    at TCPConnection._readPacket (/root/Steambooster/steam-bot-constructor/node_modules/steam-client/lib/tcp_connection.js:183:7)
    at Socket.emit (events.js:189:13)
    at emitReadable_ (_stream_readable.js:535:12)
Emitted 'error' event at:
    at SteamUser._handlers.(anonymous function) (/root/Steambooster/steam-bot-constructor/node_modules/steam-user/components/logon.js:366:9)
    at SteamUser._handleMessage (/root/Steambooster/steam-bot-constructor/node_modules/steam-user/components/messages.js:249:30)
    [... lines matching original stack trace ...]
    at emitReadable_ (_stream_readable.js:535:12)


I tested it with my trash account. i dont use 2FA with it, needs more then login details ?

**Comment by SnaBe** [comment]
If you don't want to use 2FA you'll have to remove all the code that refer to it. This includes twoFactorCode: SteamTotp.generateAuthCode(config.bot1.sharedSecret), also make sure the syntax match after you've removed the code. After that, you should be able to log in if you parse the right login information. If you've email auth enabled it will ask for the auth code that was sent too you.
